ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ no.nav.tilbakekreving.tvangsgrunnlag.ApplicationKt.module ]
    }
}

no.nav.security.jwt {
    issuers = [
        {
            issuer_name = maskinporten
            discoveryurl = ${?MASKINPORTEN_WELL_KNOWN_URL}
            accepted_audience = ${?MASKINPORTEN_CLIENT_ID}
        }
    ]
}

